version: '3.3'
services:
  client:
    image: qunis/qaf_client:latest
    networks:
      - webnet
  node1:
    image: qunis/qaf_node
    deploy:
      replicas: 1
      #restart-policy: on-failure
    depends_on:
     - redis
    networks:
      - webnet
  node2:
    image: qunis/qaf_node 
    deploy:
      replicas: 3
      #restart-policy: on-failure
    depends_on:
     - redis
    networks:
      - webnet
  nginx:
    image: qunis/qaf_nginx
    ports:
      - "80:80"
      - "443:443"
     # - "8001:8001"
     # - "8002:8002"
    networks:
      - webnet
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
       - "./redisdata:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet:

