version: '3.3'
services:
  client:
    image: qunis/qaf_client
  node1:
    image: qunis/qaf_node
    deploy:
      replicas: 1
    depends_on:
     - redis
  node2:
    image: qunis/qaf_node 
    deploy:
      replicas: 1
    depends_on:
     - redis
  nginx:
    image: qunis/qaf_nginx
    ports:
      - "80:80"
      - "443:443"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
       - "./redisdata:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
  boss:
    image: qunis/qaf_boss
    ports:
      - "8001:8001"
    depends_on:
      - redis    
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]


