apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -f .\docker-compose-kube.yml
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: boss
  name: boss
spec:
  ports:
  - name: "8001"
    port: 8001
    targetPort: 8001
  selector:
    io.kompose.service: boss
status:
  loadBalancer: {}
