apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    deployment: nginx
  name: nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        deployment: nginx
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
          - mountPath: /etc/nginx
            name: config
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: nginx-config
            items:
            - key: nginx-config
              path: nginx.conf
---

apiVersion: v1
kind: Service
metadata:
  labels:
    deployment: nginx
  name: nginx
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    deployment: nginx
  type: LoadBalancer